# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'WS6_Movie' do
  # Pods for WS6_Movie
  # pod 'AFNetworking'
  pod 'Moya', '~> 12.0'
  pod 'Kingfisher'

  target 'WS6_MovieTests' do
    inherit! :search_paths

    # Pods for testing
  end

end
